# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/fabric-baseos:_BASE_TAG_
ENV FABRIC_CFG_PATH /etc/hyperledger/fabric
RUN mkdir -p /opt/lib /var/hyperledger/production $FABRIC_CFG_PATH
COPY payload/peer /usr/local/bin
COPY payload/msscc.so /opt/lib/
ADD  payload/sampleconfig.tar.bz2 $FABRIC_CFG_PATH

COPY payload/ca.pem /certs/client/
COPY payload/cert.pem /certs/client/
COPY payload/key.pem /certs/client/
ENV CORE_VM_DOCKER_TLS_ENABLED true
ENV CORE_VM_DOCKER_TLS_CERT_FILE /certs/client/cert.pem
ENV CORE_VM_DOCKER_TLS_KEY_FILE /certs/client/key.pem
ENV CORE_VM_DOCKER_TLS_CA_FILE /certs/client/ca.pem

RUN rm -f /etc/apt/sources.list
COPY payload/sources.list /etc/apt/
RUN apt-get update \
	&& apt-get install inetutils-ping --assume-yes apt-utils \
	&& apt-get install net-tools --assume-yes apt-utils \
	&& apt-get install telnet --assume-yes apt-utils \
	&& apt-get install curl --assume-yes apt-utils
COPY payload/confcenterdownload /usr/local/bin/
COPY payload/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
